(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: pcb-NPTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Monday, 01 June 2026 at 17:41)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 2.5)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 30.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.5)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 5.0)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:    1.7500 ...  130.2500  mm)
(Y range:    4.2500 ...   71.7500  mm)

(Spindle Speed: 10000 RPM)
G21
G90
G17
G94


G01 F30.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T1
(MSG, Change to Tool Dia = 2.5000 ||| Total drills for tool T1 = 8)
M0
G00 Z15.0000
        
G01 F30.00
M03 S10000
G00 X3.0000 Y70.5000
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X3.0000 Y70.5000
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X8.0000 Y66.0000
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X8.0370 Y28.0380
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X3.5000 Y5.5000
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X46.1370 Y28.0380
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X46.1370 Y66.1380
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X129.0000 Y70.5000
G01 Z-2.5000
G01 Z0
G00 Z5.0000
G00 X128.5000 Y6.0000
G01 Z-2.5000
G01 Z0
G00 Z5.0000
M05
G00 Z0.50


